---
# tasks file for el7-prometheus

# sudo useradd --no-create-home --shell /bin/false prometheus
- name: "Create the {{ node_exporter_system_user }} user"
  user:
    name: "{{ node_exporter_system_user }}"
    comment: Prometheus metrics and alerting user
    shell: /bin/false
    create_home: false

# wget https://github.com/prometheus/node_exporter/releases/download/v*/node_exporter-*.*-amd64.tar.gz
- name: Download node_exporter binary to local folder
  become: false
  get_url:
    url: "{{ url }}"
    dest: "/tmp/{{ artifact }}"
    checksum: "sha256:{{ checksum }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack node_exporter binary
  become: false
  unarchive:
    src: "/tmp/{{ artifact }}"
    dest: "/tmp"
    creates: "/tmp/node_exporter-{{ version }}.linux-amd64/node_exporter"
  delegate_to: localhost
  check_mode: false

- name: Create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Propagate node_exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0750
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
  notify: restart node_exporter
  when: not ansible_check_mode

- name: Create the node_exporter.service from a template
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0777'
  notify: restart node_exporter
  when: not ansible_check_mode

- name: allow node_exported through the firewall
  firewalld:
    port: 9100/tcp
    permanent: yes
    immediate: yes
    state: enabled
...